# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pub" # Dart and Flutter
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      # Group all patch version updates for pub into a single pull request
      patch-updates:
        update-types:
          - "version-update:semver-patch"
