// Mocks generated by Mockito 5.4.6 from annotations
// in novelty/test/providers/novel_detail_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:novelty/database/database.dart' as _i3;
import 'package:novelty/models/download_progress.dart' as _i16;
import 'package:novelty/models/download_result.dart' as _i9;
import 'package:novelty/models/episode.dart' as _i7;
import 'package:novelty/models/novel_content_element.dart' as _i17;
import 'package:novelty/models/novel_info.dart' as _i6;
import 'package:novelty/models/novel_search_query.dart' as _i12;
import 'package:novelty/models/ranking_response.dart' as _i11;
import 'package:novelty/repositories/novel_repository.dart' as _i13;
import 'package:novelty/services/api_service.dart' as _i8;
import 'package:novelty/utils/settings_provider.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$NovelsTable_1 extends _i1.SmartFake implements _i3.$NovelsTable {
  _Fake$NovelsTable_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$HistoryTable_2 extends _i1.SmartFake implements _i3.$HistoryTable {
  _Fake$HistoryTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EpisodesTable_3 extends _i1.SmartFake
    implements _i3.$EpisodesTable {
  _Fake$EpisodesTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DownloadedNovelsTable_4 extends _i1.SmartFake
    implements _i3.$DownloadedNovelsTable {
  _Fake$DownloadedNovelsTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DownloadedEpisodesTable_5 extends _i1.SmartFake
    implements _i3.$DownloadedEpisodesTable {
  _Fake$DownloadedEpisodesTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LibraryNovelsTable_6 extends _i1.SmartFake
    implements _i3.$LibraryNovelsTable {
  _Fake$LibraryNovelsTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BookmarksTable_7 extends _i1.SmartFake
    implements _i3.$BookmarksTable {
  _Fake$BookmarksTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_8 extends _i1.SmartFake
    implements _i3.$AppDatabaseManager {
  _Fake$AppDatabaseManager_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_9 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_10 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_11 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_12 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_13 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_14 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_15 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_16 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_17<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_18<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_19<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_20<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake
    implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_21<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_22<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_23<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_24<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_25 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNovelInfo_26 extends _i1.SmartFake implements _i6.NovelInfo {
  _FakeNovelInfo_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEpisode_27 extends _i1.SmartFake implements _i7.Episode {
  _FakeEpisode_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiService_28 extends _i1.SmartFake implements _i8.ApiService {
  _FakeApiService_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadResult_29 extends _i1.SmartFake
    implements _i9.DownloadResult {
  _FakeDownloadResult_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i3.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);

  @override
  _i3.$NovelsTable get novels =>
      (super.noSuchMethod(
            Invocation.getter(#novels),
            returnValue: _Fake$NovelsTable_1(this, Invocation.getter(#novels)),
          )
          as _i3.$NovelsTable);

  @override
  _i3.$HistoryTable get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: _Fake$HistoryTable_2(
              this,
              Invocation.getter(#history),
            ),
          )
          as _i3.$HistoryTable);

  @override
  _i3.$EpisodesTable get episodes =>
      (super.noSuchMethod(
            Invocation.getter(#episodes),
            returnValue: _Fake$EpisodesTable_3(
              this,
              Invocation.getter(#episodes),
            ),
          )
          as _i3.$EpisodesTable);

  @override
  _i3.$DownloadedNovelsTable get downloadedNovels =>
      (super.noSuchMethod(
            Invocation.getter(#downloadedNovels),
            returnValue: _Fake$DownloadedNovelsTable_4(
              this,
              Invocation.getter(#downloadedNovels),
            ),
          )
          as _i3.$DownloadedNovelsTable);

  @override
  _i3.$DownloadedEpisodesTable get downloadedEpisodes =>
      (super.noSuchMethod(
            Invocation.getter(#downloadedEpisodes),
            returnValue: _Fake$DownloadedEpisodesTable_5(
              this,
              Invocation.getter(#downloadedEpisodes),
            ),
          )
          as _i3.$DownloadedEpisodesTable);

  @override
  _i3.$LibraryNovelsTable get libraryNovels =>
      (super.noSuchMethod(
            Invocation.getter(#libraryNovels),
            returnValue: _Fake$LibraryNovelsTable_6(
              this,
              Invocation.getter(#libraryNovels),
            ),
          )
          as _i3.$LibraryNovelsTable);

  @override
  _i3.$BookmarksTable get bookmarks =>
      (super.noSuchMethod(
            Invocation.getter(#bookmarks),
            returnValue: _Fake$BookmarksTable_7(
              this,
              Invocation.getter(#bookmarks),
            ),
          )
          as _i3.$BookmarksTable);

  @override
  _i3.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_8(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i3.$AppDatabaseManager);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
          )
          as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i2.DatabaseSchemaEntity>[],
          )
          as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_9(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_10(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_11(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i2.StreamQueryUpdateRules);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_12(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i10.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_13(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_14(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_15(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<_i3.Novel?> getNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getNovel, [ncode]),
            returnValue: _i5.Future<_i3.Novel?>.value(),
          )
          as _i5.Future<_i3.Novel?>);

  @override
  _i5.Future<int> addToLibrary(_i3.LibraryNovelsCompanion? novel) =>
      (super.noSuchMethod(
            Invocation.method(#addToLibrary, [novel]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> removeFromLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromLibrary, [ncode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.LibraryNovel>> getLibraryNovels() =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryNovels, []),
            returnValue: _i5.Future<List<_i3.LibraryNovel>>.value(
              <_i3.LibraryNovel>[],
            ),
          )
          as _i5.Future<List<_i3.LibraryNovel>>);

  @override
  _i5.Future<List<_i3.Novel>> getLibraryNovelsWithDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryNovelsWithDetails, []),
            returnValue: _i5.Future<List<_i3.Novel>>.value(<_i3.Novel>[]),
          )
          as _i5.Future<List<_i3.Novel>>);

  @override
  _i5.Stream<List<_i3.Novel>> watchLibraryNovelsWithDetails() =>
      (super.noSuchMethod(
            Invocation.method(#watchLibraryNovelsWithDetails, []),
            returnValue: _i5.Stream<List<_i3.Novel>>.empty(),
          )
          as _i5.Stream<List<_i3.Novel>>);

  @override
  _i5.Future<bool> isInLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#isInLibrary, [ncode]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<bool> watchIsInLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchIsInLibrary, [ncode]),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Stream<bool> watchIsFavorite(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchIsFavorite, [ncode]),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Future<int> insertNovel(_i3.NovelsCompanion? novel) =>
      (super.noSuchMethod(
            Invocation.method(#insertNovel, [novel]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNovel, [ncode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> addToHistory(_i3.HistoryCompanion? history) =>
      (super.noSuchMethod(
            Invocation.method(#addToHistory, [history]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.HistoryData>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i5.Future<List<_i3.HistoryData>>.value(
              <_i3.HistoryData>[],
            ),
          )
          as _i5.Future<List<_i3.HistoryData>>);

  @override
  _i5.Stream<List<_i3.HistoryData>> watchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#watchHistory, []),
            returnValue: _i5.Stream<List<_i3.HistoryData>>.empty(),
          )
          as _i5.Stream<List<_i3.HistoryData>>);

  @override
  _i5.Future<int> deleteHistory(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHistory, [ncode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> clearHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> insertEpisode(_i3.EpisodesCompanion? episode) =>
      (super.noSuchMethod(
            Invocation.method(#insertEpisode, [episode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.Episode?> getEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisode, [ncode, episode]),
            returnValue: _i5.Future<_i3.Episode?>.value(),
          )
          as _i5.Future<_i3.Episode?>);

  @override
  _i5.Future<int> insertDownloadedEpisode(
    _i3.DownloadedEpisodesCompanion? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertDownloadedEpisode, [episode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.DownloadedEpisode?> getDownloadedEpisode(
    String? ncode,
    int? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedEpisode, [ncode, episode]),
            returnValue: _i5.Future<_i3.DownloadedEpisode?>.value(),
          )
          as _i5.Future<_i3.DownloadedEpisode?>);

  @override
  _i5.Future<int> deleteDownloadedEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedEpisode, [ncode, episode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> upsertDownloadedNovel(_i3.DownloadedNovelsCompanion? novel) =>
      (super.noSuchMethod(
            Invocation.method(#upsertDownloadedNovel, [novel]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.DownloadedNovel?> getDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedNovel, [ncode]),
            returnValue: _i5.Future<_i3.DownloadedNovel?>.value(),
          )
          as _i5.Future<_i3.DownloadedNovel?>);

  @override
  _i5.Stream<_i3.DownloadedNovel?> watchDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchDownloadedNovel, [ncode]),
            returnValue: _i5.Stream<_i3.DownloadedNovel?>.empty(),
          )
          as _i5.Stream<_i3.DownloadedNovel?>);

  @override
  _i5.Future<int> deleteDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedNovel, [ncode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> addBookmark(_i3.BookmarksCompanion? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#addBookmark, [bookmark]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Bookmark>> getBookmarks(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarks, [ncode]),
            returnValue: _i5.Future<List<_i3.Bookmark>>.value(<_i3.Bookmark>[]),
          )
          as _i5.Future<List<_i3.Bookmark>>);

  @override
  _i5.Future<int> deleteBookmark(String? ncode, int? episode, int? position) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [ncode, episode, position]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i2.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_16(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i10.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_18<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_19<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_20<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_21<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_22<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_23<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
          )
          as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_24<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_24<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_25(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_25(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i8.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, _i6.NovelInfo>> fetchMultipleNovelsInfo(
    List<String>? ncodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMultipleNovelsInfo, [ncodes]),
            returnValue: _i5.Future<Map<String, _i6.NovelInfo>>.value(
              <String, _i6.NovelInfo>{},
            ),
          )
          as _i5.Future<Map<String, _i6.NovelInfo>>);

  @override
  _i5.Future<_i6.NovelInfo> fetchBasicNovelInfo(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBasicNovelInfo, [ncode]),
            returnValue: _i5.Future<_i6.NovelInfo>.value(
              _FakeNovelInfo_26(
                this,
                Invocation.method(#fetchBasicNovelInfo, [ncode]),
              ),
            ),
          )
          as _i5.Future<_i6.NovelInfo>);

  @override
  _i5.Future<List<_i7.Episode>> fetchEpisodeList(String? ncode, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisodeList, [ncode, page]),
            returnValue: _i5.Future<List<_i7.Episode>>.value(<_i7.Episode>[]),
          )
          as _i5.Future<List<_i7.Episode>>);

  @override
  _i5.Future<_i6.NovelInfo> fetchNovelInfo(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNovelInfo, [ncode]),
            returnValue: _i5.Future<_i6.NovelInfo>.value(
              _FakeNovelInfo_26(
                this,
                Invocation.method(#fetchNovelInfo, [ncode]),
              ),
            ),
          )
          as _i5.Future<_i6.NovelInfo>);

  @override
  _i5.Future<_i7.Episode> fetchEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisode, [ncode, episode]),
            returnValue: _i5.Future<_i7.Episode>.value(
              _FakeEpisode_27(
                this,
                Invocation.method(#fetchEpisode, [ncode, episode]),
              ),
            ),
          )
          as _i5.Future<_i7.Episode>);

  @override
  _i5.Future<List<_i11.RankingResponse>> searchNovels(
    _i12.NovelSearchQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchNovels, [query]),
            returnValue: _i5.Future<List<_i11.RankingResponse>>.value(
              <_i11.RankingResponse>[],
            ),
          )
          as _i5.Future<List<_i11.RankingResponse>>);

  @override
  _i5.Future<List<_i11.RankingResponse>> fetchRanking(String? rankingType) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRanking, [rankingType]),
            returnValue: _i5.Future<List<_i11.RankingResponse>>.value(
              <_i11.RankingResponse>[],
            ),
          )
          as _i5.Future<List<_i11.RankingResponse>>);
}

/// A class which mocks [NovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNovelRepository extends _i1.Mock implements _i13.NovelRepository {
  MockNovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i10.dummyValue<_i14.Ref>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i14.Ref);

  @override
  _i8.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_28(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i8.ApiService);

  @override
  _i14.AsyncValue<_i15.AppSettings> get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _i10.dummyValue<_i14.AsyncValue<_i15.AppSettings>>(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i14.AsyncValue<_i15.AppSettings>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<_i16.DownloadProgress> watchDownloadProgress(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchDownloadProgress, [ncode]),
            returnValue: _i5.Stream<_i16.DownloadProgress>.empty(),
          )
          as _i5.Stream<_i16.DownloadProgress>);

  @override
  _i5.Future<bool> addNovelToLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#addNovelToLibrary, [ncode]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i17.NovelContentElement>> getEpisode(
    String? ncode,
    int? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisode, [ncode, episode]),
            returnValue: _i5.Future<List<_i17.NovelContentElement>>.value(
              <_i17.NovelContentElement>[],
            ),
          )
          as _i5.Future<List<_i17.NovelContentElement>>);

  @override
  _i5.Future<void> downloadEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#downloadEpisode, [ncode, episode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> downloadNovel(String? ncode, int? totalEpisodes) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNovel, [ncode, totalEpisodes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteDownloadedEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedEpisode, [ncode, episode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedNovel, [ncode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<bool> isEpisodeDownloaded(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#isEpisodeDownloaded, [ncode, episode]),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Stream<bool> isNovelDownloaded(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#isNovelDownloaded, [ncode]),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Future<_i9.DownloadResult> downloadNovelWithPermission(
    String? ncode,
    int? totalEpisodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNovelWithPermission, [
              ncode,
              totalEpisodes,
            ]),
            returnValue: _i5.Future<_i9.DownloadResult>.value(
              _FakeDownloadResult_29(
                this,
                Invocation.method(#downloadNovelWithPermission, [
                  ncode,
                  totalEpisodes,
                ]),
              ),
            ),
          )
          as _i5.Future<_i9.DownloadResult>);
}
