include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    invalid_annotation_target: ignore
    public_member_api_docs: ignore
    document_ignores: ignore
  exclude:
    - lib/src/models/*.g.dart
    - lib/src/models/*.freezed.dart
