// Mocks generated by Mockito 5.4.6 from annotations
// in novelty/test/screens/data_storage_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:novelty/services/backup_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupService extends _i1.Mock implements _i2.BackupService {
  MockBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> exportLibraryData() =>
      (super.noSuchMethod(
            Invocation.method(#exportLibraryData, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> exportHistoryData() =>
      (super.noSuchMethod(
            Invocation.method(#exportHistoryData, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> importLibraryData(Map<String, dynamic>? jsonData) =>
      (super.noSuchMethod(
            Invocation.method(#importLibraryData, [jsonData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> importHistoryData(Map<String, dynamic>? jsonData) =>
      (super.noSuchMethod(
            Invocation.method(#importHistoryData, [jsonData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> exportLibraryToFile() =>
      (super.noSuchMethod(
            Invocation.method(#exportLibraryToFile, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> exportHistoryToFile() =>
      (super.noSuchMethod(
            Invocation.method(#exportHistoryToFile, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<int> importLibraryFromFile() =>
      (super.noSuchMethod(
            Invocation.method(#importLibraryFromFile, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> importHistoryFromFile() =>
      (super.noSuchMethod(
            Invocation.method(#importHistoryFromFile, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
