// Mocks generated by Mockito 5.4.6 from annotations
// in novelty/test/screens/novel_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:narou_parser/narou_parser.dart' as _i10;
import 'package:novelty/models/download_progress.dart' as _i9;
import 'package:novelty/models/download_result.dart' as _i3;
import 'package:novelty/models/episode.dart' as _i11;
import 'package:novelty/models/novel_info.dart' as _i12;
import 'package:novelty/repositories/novel_repository.dart' as _i4;
import 'package:novelty/services/api_service.dart' as _i2;
import 'package:novelty/utils/settings_provider.dart' as _i7;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadResult_1 extends _i1.SmartFake
    implements _i3.DownloadResult {
  _FakeDownloadResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNovelRepository extends _i1.Mock implements _i4.NovelRepository {
  MockNovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i6.dummyValue<_i5.Ref>(this, Invocation.getter(#ref)),
          )
          as _i5.Ref);

  @override
  _i2.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.ApiService);

  @override
  _i5.AsyncValue<_i7.AppSettings> get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _i6.dummyValue<_i5.AsyncValue<_i7.AppSettings>>(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i5.AsyncValue<_i7.AppSettings>);

  @override
  void invalidateSwrCache(String? key) => super.noSuchMethod(
    Invocation.method(#invalidateSwrCache, [key]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Stream<_i9.DownloadProgress> watchDownloadProgress(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchDownloadProgress, [ncode]),
            returnValue: _i8.Stream<_i9.DownloadProgress>.empty(),
          )
          as _i8.Stream<_i9.DownloadProgress>);

  @override
  _i8.Future<bool> addNovelToLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#addNovelToLibrary, [ncode]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> removeFromLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromLibrary, [ncode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addToHistory({
    required String? ncode,
    required String? title,
    required String? writer,
    required int? lastEpisode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addToHistory, [], {
              #ncode: ncode,
              #title: title,
              #writer: writer,
              #lastEpisode: lastEpisode,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteHistory(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHistory, [ncode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> downloadSingleEpisode(
    String? ncode,
    int? episode, {
    String? revised,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadSingleEpisode,
              [ncode, episode],
              {#revised: revised},
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i10.NovelContentElement>> getEpisode(
    String? ncode,
    int? episode, {
    String? revised,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEpisode,
              [ncode, episode],
              {#revised: revised},
            ),
            returnValue: _i8.Future<List<_i10.NovelContentElement>>.value(
              <_i10.NovelContentElement>[],
            ),
          )
          as _i8.Future<List<_i10.NovelContentElement>>);

  @override
  _i8.Future<void> downloadEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#downloadEpisode, [ncode, episode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> downloadNovel(String? ncode, int? totalEpisodes) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNovel, [ncode, totalEpisodes]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteDownloadedEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedEpisode, [ncode, episode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedNovel, [ncode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<bool> isEpisodeDownloaded(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#isEpisodeDownloaded, [ncode, episode]),
            returnValue: _i8.Stream<bool>.empty(),
          )
          as _i8.Stream<bool>);

  @override
  _i8.Future<_i3.DownloadResult> downloadNovelWithResult(
    String? ncode,
    int? totalEpisodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNovelWithResult, [ncode, totalEpisodes]),
            returnValue: _i8.Future<_i3.DownloadResult>.value(
              _FakeDownloadResult_1(
                this,
                Invocation.method(#downloadNovelWithResult, [
                  ncode,
                  totalEpisodes,
                ]),
              ),
            ),
          )
          as _i8.Future<_i3.DownloadResult>);

  @override
  _i8.Future<List<_i11.Episode>> fetchEpisodeList(String? ncode, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisodeList, [ncode, page]),
            returnValue: _i8.Future<List<_i11.Episode>>.value(<_i11.Episode>[]),
          )
          as _i8.Future<List<_i11.Episode>>);

  @override
  _i8.Stream<_i12.NovelInfo> watchNovelInfo(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchNovelInfo, [ncode]),
            returnValue: _i8.Stream<_i12.NovelInfo>.empty(),
          )
          as _i8.Stream<_i12.NovelInfo>);

  @override
  _i8.Stream<List<_i11.Episode>> watchEpisodeList(String? ncode, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#watchEpisodeList, [ncode, page]),
            returnValue: _i8.Stream<List<_i11.Episode>>.empty(),
          )
          as _i8.Stream<List<_i11.Episode>>);

  @override
  _i8.Stream<int?> watchLastReadEpisode(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchLastReadEpisode, [ncode]),
            returnValue: _i8.Stream<int?>.empty(),
          )
          as _i8.Stream<int?>);
}
