// Mocks generated by Mockito 5.4.6 from annotations
// in novelty/test/repositories/novel_repository_library_update_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:drift/drift.dart' as _i4;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:novelty/database/database.dart' as _i5;
import 'package:novelty/models/episode.dart' as _i3;
import 'package:novelty/models/novel_info.dart' as _i2;
import 'package:novelty/models/novel_search_query.dart' as _i10;
import 'package:novelty/models/ranking_response.dart' as _i9;
import 'package:novelty/services/api_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNovelInfo_0 extends _i1.SmartFake implements _i2.NovelInfo {
  _FakeNovelInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEpisode_1 extends _i1.SmartFake implements _i3.Episode {
  _FakeEpisode_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_2 extends _i1.SmartFake
    implements _i4.MigrationStrategy {
  _FakeMigrationStrategy_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$NovelsTable_3 extends _i1.SmartFake implements _i5.$NovelsTable {
  _Fake$NovelsTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$HistoryTable_4 extends _i1.SmartFake implements _i5.$HistoryTable {
  _Fake$HistoryTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EpisodesTable_5 extends _i1.SmartFake
    implements _i5.$EpisodesTable {
  _Fake$EpisodesTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DownloadedNovelsTable_6 extends _i1.SmartFake
    implements _i5.$DownloadedNovelsTable {
  _Fake$DownloadedNovelsTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DownloadedEpisodesTable_7 extends _i1.SmartFake
    implements _i5.$DownloadedEpisodesTable {
  _Fake$DownloadedEpisodesTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LibraryNovelsTable_8 extends _i1.SmartFake
    implements _i5.$LibraryNovelsTable {
  _Fake$LibraryNovelsTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BookmarksTable_9 extends _i1.SmartFake
    implements _i5.$BookmarksTable {
  _Fake$BookmarksTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_10 extends _i1.SmartFake
    implements _i5.$AppDatabaseManager {
  _Fake$AppDatabaseManager_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_11 extends _i1.SmartFake
    implements _i4.GeneratedDatabase {
  _FakeGeneratedDatabase_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_12 extends _i1.SmartFake
    implements _i4.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_13 extends _i1.SmartFake
    implements _i4.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_14 extends _i1.SmartFake
    implements _i4.DatabaseConnection {
  _FakeDatabaseConnection_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_15 extends _i1.SmartFake implements _i4.QueryExecutor {
  _FakeQueryExecutor_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_16 extends _i1.SmartFake
    implements _i6.StreamQueryStore {
  _FakeStreamQueryStore_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_17 extends _i1.SmartFake
    implements _i4.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_18 extends _i1.SmartFake implements _i4.Migrator {
  _FakeMigrator_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_19<T1> extends _i1.SmartFake implements _i7.Future<T1> {
  _FakeFuture_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_20<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.InsertStatement<T1, D1> {
  _FakeInsertStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_21<T extends _i4.Table, D> extends _i1.SmartFake
    implements _i4.UpdateStatement<T, D> {
  _FakeUpdateStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_22<T1 extends _i4.HasResultSet, D>
    extends _i1.SmartFake
    implements _i4.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_23<FirstT extends _i4.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i4.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_24<Row> extends _i1.SmartFake
    implements _i4.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_25<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_26<T> extends _i1.SmartFake implements _i4.Selectable<T> {
  _FakeSelectable_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_27 extends _i1.SmartFake
    implements _i4.GenerationContext {
  _FakeGenerationContext_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i8.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<Map<String, _i2.NovelInfo>> fetchMultipleNovelsInfo(
    List<String>? ncodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMultipleNovelsInfo, [ncodes]),
            returnValue: _i7.Future<Map<String, _i2.NovelInfo>>.value(
              <String, _i2.NovelInfo>{},
            ),
          )
          as _i7.Future<Map<String, _i2.NovelInfo>>);

  @override
  _i7.Future<_i2.NovelInfo> fetchBasicNovelInfo(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBasicNovelInfo, [ncode]),
            returnValue: _i7.Future<_i2.NovelInfo>.value(
              _FakeNovelInfo_0(
                this,
                Invocation.method(#fetchBasicNovelInfo, [ncode]),
              ),
            ),
          )
          as _i7.Future<_i2.NovelInfo>);

  @override
  _i7.Future<List<_i3.Episode>> fetchEpisodeList(String? ncode, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisodeList, [ncode, page]),
            returnValue: _i7.Future<List<_i3.Episode>>.value(<_i3.Episode>[]),
          )
          as _i7.Future<List<_i3.Episode>>);

  @override
  _i7.Future<_i2.NovelInfo> fetchNovelInfo(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNovelInfo, [ncode]),
            returnValue: _i7.Future<_i2.NovelInfo>.value(
              _FakeNovelInfo_0(
                this,
                Invocation.method(#fetchNovelInfo, [ncode]),
              ),
            ),
          )
          as _i7.Future<_i2.NovelInfo>);

  @override
  _i7.Future<_i3.Episode> fetchEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisode, [ncode, episode]),
            returnValue: _i7.Future<_i3.Episode>.value(
              _FakeEpisode_1(
                this,
                Invocation.method(#fetchEpisode, [ncode, episode]),
              ),
            ),
          )
          as _i7.Future<_i3.Episode>);

  @override
  _i7.Future<List<_i9.RankingResponse>> searchNovels(
    _i10.NovelSearchQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchNovels, [query]),
            returnValue: _i7.Future<List<_i9.RankingResponse>>.value(
              <_i9.RankingResponse>[],
            ),
          )
          as _i7.Future<List<_i9.RankingResponse>>);

  @override
  _i7.Future<List<_i9.RankingResponse>> fetchRanking(String? rankingType) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRanking, [rankingType]),
            returnValue: _i7.Future<List<_i9.RankingResponse>>.value(
              <_i9.RankingResponse>[],
            ),
          )
          as _i7.Future<List<_i9.RankingResponse>>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i5.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i4.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_2(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i4.MigrationStrategy);

  @override
  _i5.$NovelsTable get novels =>
      (super.noSuchMethod(
            Invocation.getter(#novels),
            returnValue: _Fake$NovelsTable_3(this, Invocation.getter(#novels)),
          )
          as _i5.$NovelsTable);

  @override
  _i5.$HistoryTable get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: _Fake$HistoryTable_4(
              this,
              Invocation.getter(#history),
            ),
          )
          as _i5.$HistoryTable);

  @override
  _i5.$EpisodesTable get episodes =>
      (super.noSuchMethod(
            Invocation.getter(#episodes),
            returnValue: _Fake$EpisodesTable_5(
              this,
              Invocation.getter(#episodes),
            ),
          )
          as _i5.$EpisodesTable);

  @override
  _i5.$DownloadedNovelsTable get downloadedNovels =>
      (super.noSuchMethod(
            Invocation.getter(#downloadedNovels),
            returnValue: _Fake$DownloadedNovelsTable_6(
              this,
              Invocation.getter(#downloadedNovels),
            ),
          )
          as _i5.$DownloadedNovelsTable);

  @override
  _i5.$DownloadedEpisodesTable get downloadedEpisodes =>
      (super.noSuchMethod(
            Invocation.getter(#downloadedEpisodes),
            returnValue: _Fake$DownloadedEpisodesTable_7(
              this,
              Invocation.getter(#downloadedEpisodes),
            ),
          )
          as _i5.$DownloadedEpisodesTable);

  @override
  _i5.$LibraryNovelsTable get libraryNovels =>
      (super.noSuchMethod(
            Invocation.getter(#libraryNovels),
            returnValue: _Fake$LibraryNovelsTable_8(
              this,
              Invocation.getter(#libraryNovels),
            ),
          )
          as _i5.$LibraryNovelsTable);

  @override
  _i5.$BookmarksTable get bookmarks =>
      (super.noSuchMethod(
            Invocation.getter(#bookmarks),
            returnValue: _Fake$BookmarksTable_9(
              this,
              Invocation.getter(#bookmarks),
            ),
          )
          as _i5.$BookmarksTable);

  @override
  _i5.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_10(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i5.$AppDatabaseManager);

  @override
  Iterable<_i4.TableInfo<_i4.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i4.TableInfo<_i4.Table, Object?>>[],
          )
          as Iterable<_i4.TableInfo<_i4.Table, Object?>>);

  @override
  List<_i4.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i4.DatabaseSchemaEntity>[],
          )
          as List<_i4.DatabaseSchemaEntity>);

  @override
  _i4.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_11(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i4.GeneratedDatabase);

  @override
  _i4.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_12(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i4.DriftDatabaseOptions);

  @override
  _i4.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_13(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i4.StreamQueryUpdateRules);

  @override
  _i4.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_14(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i4.DatabaseConnection);

  @override
  _i4.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i11.dummyValue<_i4.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i4.SqlTypes);

  @override
  _i4.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_15(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i4.QueryExecutor);

  @override
  _i6.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_16(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i6.StreamQueryStore);

  @override
  _i4.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_17(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i4.DatabaseConnectionUser);

  @override
  _i7.Future<_i5.Novel?> getNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getNovel, [ncode]),
            returnValue: _i7.Future<_i5.Novel?>.value(),
          )
          as _i7.Future<_i5.Novel?>);

  @override
  _i7.Future<int> addToLibrary(_i5.LibraryNovelsCompanion? novel) =>
      (super.noSuchMethod(
            Invocation.method(#addToLibrary, [novel]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeFromLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromLibrary, [ncode]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i5.LibraryNovel>> getLibraryNovels() =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryNovels, []),
            returnValue: _i7.Future<List<_i5.LibraryNovel>>.value(
              <_i5.LibraryNovel>[],
            ),
          )
          as _i7.Future<List<_i5.LibraryNovel>>);

  @override
  _i7.Future<bool> isInLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#isInLibrary, [ncode]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Stream<bool> watchIsInLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchIsInLibrary, [ncode]),
            returnValue: _i7.Stream<bool>.empty(),
          )
          as _i7.Stream<bool>);

  @override
  _i7.Stream<bool> watchIsFavorite(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchIsFavorite, [ncode]),
            returnValue: _i7.Stream<bool>.empty(),
          )
          as _i7.Stream<bool>);

  @override
  _i7.Future<int> insertNovel(_i5.NovelsCompanion? novel) =>
      (super.noSuchMethod(
            Invocation.method(#insertNovel, [novel]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> deleteNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNovel, [ncode]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> updateNovelFromApi(
    String? ncode,
    _i2.NovelInfo? apiNovelInfo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNovelFromApi, [ncode, apiNovelInfo]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> addToHistory(_i5.HistoryCompanion? history) =>
      (super.noSuchMethod(
            Invocation.method(#addToHistory, [history]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i5.HistoryData>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i7.Future<List<_i5.HistoryData>>.value(
              <_i5.HistoryData>[],
            ),
          )
          as _i7.Future<List<_i5.HistoryData>>);

  @override
  _i7.Future<int> deleteHistory(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHistory, [ncode]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> clearHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, []),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> insertEpisode(_i5.EpisodesCompanion? episode) =>
      (super.noSuchMethod(
            Invocation.method(#insertEpisode, [episode]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<_i5.Episode?> getEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisode, [ncode, episode]),
            returnValue: _i7.Future<_i5.Episode?>.value(),
          )
          as _i7.Future<_i5.Episode?>);

  @override
  _i7.Future<int> insertDownloadedEpisode(
    _i5.DownloadedEpisodesCompanion? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertDownloadedEpisode, [episode]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<_i5.DownloadedEpisode?> getDownloadedEpisode(
    String? ncode,
    int? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedEpisode, [ncode, episode]),
            returnValue: _i7.Future<_i5.DownloadedEpisode?>.value(),
          )
          as _i7.Future<_i5.DownloadedEpisode?>);

  @override
  _i7.Future<int> deleteDownloadedEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedEpisode, [ncode, episode]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> upsertDownloadedNovel(_i5.DownloadedNovelsCompanion? novel) =>
      (super.noSuchMethod(
            Invocation.method(#upsertDownloadedNovel, [novel]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<_i5.DownloadedNovel?> getDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedNovel, [ncode]),
            returnValue: _i7.Future<_i5.DownloadedNovel?>.value(),
          )
          as _i7.Future<_i5.DownloadedNovel?>);

  @override
  _i7.Stream<_i5.DownloadedNovel?> watchDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchDownloadedNovel, [ncode]),
            returnValue: _i7.Stream<_i5.DownloadedNovel?>.empty(),
          )
          as _i7.Stream<_i5.DownloadedNovel?>);

  @override
  _i7.Future<int> deleteDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedNovel, [ncode]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> addBookmark(_i5.BookmarksCompanion? bookmark) =>
      (super.noSuchMethod(
            Invocation.method(#addBookmark, [bookmark]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i5.Bookmark>> getBookmarks(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarks, [ncode]),
            returnValue: _i7.Future<List<_i5.Bookmark>>.value(<_i5.Bookmark>[]),
          )
          as _i7.Future<List<_i5.Bookmark>>);

  @override
  _i7.Future<int> deleteBookmark(String? ncode, int? episode, int? position) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [ncode, episode, position]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i4.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_18(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i4.Migrator);

  @override
  _i7.Future<void> beforeOpen(
    _i4.QueryExecutor? executor,
    _i4.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Stream<T> createStream<T extends Object>(
    _i6.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i7.Stream<T>.empty(),
          )
          as _i7.Stream<T>);

  @override
  T alias<T, D>(_i4.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i11.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i4.TableInfo<_i4.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i4.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Stream<Set<_i4.TableUpdate>> tableUpdates([
    _i4.TableUpdateQuery? query = const _i4.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i7.Stream<Set<_i4.TableUpdate>>.empty(),
          )
          as _i7.Stream<Set<_i4.TableUpdate>>);

  @override
  _i7.Future<T> doWhenOpened<T>(
    _i7.FutureOr<T> Function(_i4.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_19<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i7.Future<T>);

  @override
  _i4.InsertStatement<T, D> into<T extends _i4.Table, D>(
    _i4.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_20<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i4.InsertStatement<T, D>);

  @override
  _i4.UpdateStatement<Tbl, R> update<Tbl extends _i4.Table, R>(
    _i4.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_21<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i4.UpdateStatement<Tbl, R>);

  @override
  _i4.SimpleSelectStatement<T, R> select<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_22<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i4.SimpleSelectStatement<T, R>);

  @override
  _i4.JoinedSelectStatement<T, R> selectOnly<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_23<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i4.JoinedSelectStatement<T, R>);

  @override
  _i4.BaseSelectStatement<_i4.TypedResult> selectExpressions(
    Iterable<_i4.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_24<_i4.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i4.BaseSelectStatement<_i4.TypedResult>);

  @override
  _i4.DeleteStatement<T, D> delete<T extends _i4.Table, D>(
    _i4.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_25<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i4.DeleteStatement<T, D>);

  @override
  _i7.Future<int> customUpdate(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> customInsert(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i4.QueryRow>> customWriteReturning(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i7.Future<List<_i4.QueryRow>>.value(<_i4.QueryRow>[]),
          )
          as _i7.Future<List<_i4.QueryRow>>);

  @override
  _i4.Selectable<_i4.QueryRow> customSelect(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_26<_i4.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i4.Selectable<_i4.QueryRow>);

  @override
  _i4.Selectable<_i4.QueryRow> customSelectQuery(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_26<_i4.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i4.Selectable<_i4.QueryRow>);

  @override
  _i7.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<T> transaction<T>(
    _i7.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_19<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i7.Future<T>);

  @override
  _i7.Future<T> exclusively<T>(_i7.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_19<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i7.Future<T>);

  @override
  _i7.Future<void> batch(_i7.FutureOr<void> Function(_i4.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<T> runWithInterceptor<T>(
    _i7.Future<T> Function()? action, {
    required _i4.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_19<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i7.Future<T>);

  @override
  _i4.GenerationContext $write(
    _i4.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_27(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i4.GenerationContext);

  @override
  _i4.GenerationContext $writeInsertable(
    _i4.TableInfo<_i4.Table, dynamic>? table,
    _i4.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_27(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i4.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
