name: Release after PR merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: read

    steps:
      # 1. マージコミットを効率的にチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 2 # マージコミットと、その親(base.sha)の2つを取得

      # 2. このPRの変更内容(diff)だけを取得
      # Squash Mergeされたコミットの差分を取得 (HEAD~1 は base.sha を指す)
      - name: Get commits for release notes
        id: get_commits
        run: |
          COMMITS=$(git log --patch HEAD~1..HEAD)
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # 3. Geminiでリリースノートを生成
      - name: Generate release notes with Gemini
        uses: google-gemini/gemini-cli-action@main
        id: generate_release_notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITS_HISTORY: ${{ env.COMMITS }}
          REPOSITORY: ${{ github.repository }}
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            あなたは、GitHubリポジトリのリリースノートを生成するAIアシスタントです。
            以下のタスクに指定した作業以外を行わないでください。

            ## タスク
            ### 1. リリースノートの作成
            以下のコミット履歴（メッセージと変更差分）を元に、簡潔でわかりやすいリリースノートを作成してください。
            リリースノートは、以下のセクションに分けてください。

            **ルール**
            - Markdown形式で出力してください。
            - リリースノートの本文のみを出力し、それ以外の前置きや挨拶などは含めないでください。
            - ユーザーが理解しやすい言葉遣いを心がけてください。
            - 新機能、バグ修正、改善点などを明確に区別してください。
            - コミットメッセージに `#` と数字がある場合、それは関連するPR番号である可能性が高いので、そのように出力に含めてください。例: 機能Aを追加 (#123)
            - 変更差分(diff)を深く分析し、コミットメッセージだけでは分からない変更の意図や内容を汲み取って、リリースノートに反映してください。

            **テンプレート**
            以下の構成に従ってリリースノートを作成してください（すべてのセクションが存在する必要はありません）:

            ```md
            ## 新機能
            - 説明内容A(必要に応じて関連PR番号を記載) 例: フィルター機能を追加 (#45)

            ## 変更
            - 説明内容B(必要に応じて関連PR番号を記載) 例: UIデザインを刷新 (#60)

            ## バグ修正
            - 説明内容C(必要に応じて関連PR番号を記載) 例: ログイン時にクラッシュする不具合を修正 (#48)

            ## 改善
            - 説明内容D(必要に応じて関連PR番号を記載) 例: ページ読み込み速度を最適化 (#50)

            ## 既知の問題
            - 説明内容E(必要に応じて関連PR番号を記載) 例: 特定の条件下でデータが同期されない問題 (#75)

            ## 非推奨・削除
            - 説明内容F(必要に応じて関連PR番号を記載) 例: 古いAPIエンドポイントを非推奨化 (#80)

            ## セキュリティ
            - 説明内容G(必要に応じて関連PR番号を記載) 例: クロスサイトスクリプティングの脆弱性を修正 (#85)

            ## その他
            - 説明内容H(必要に応じて関連PR番号を記載) 例: ドキュメントのタイポ修正 (#53)
            ```

            ---
            **コミット履歴 (git log --patch の出力):**
            ${{ env.COMMITS_HISTORY }}
            ---

            **利用可能な情報**
            - リポジトリ: ${{ env.REPOSITORY }}
            - 新しいバージョンタグ: ${{ env.LATEST_TAG }}

            ### 2. リリースノートのファイル出力
            生成したリリースノートを、`RELEASE_NOTES.md`に対して上書きしてください。

            ### 3. リリースノートの存在確認
            リリースノートが正常に出力されたかを確認するため、`cat -n RELEASE_NOTES.md`を実行してください。

      # 4. 生成されたリリースノートをファイルに書き込む
      - name: Write release notes to file
        run: echo "${{ steps.generate_release_notes.outputs.gemini-response }}" > RELEASE_NOTES.md

      # 5. 新しいバージョンを決定
      - name: Determine new version
        id: versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # gh CLIで最新のリリース情報を取得
          PREVIOUS_TAG=$(gh release list --limit 1 --json tagName -q '.[0].tagName' 2>/dev/null || echo "v0.0.0")
          VERSION=${PREVIOUS_TAG#v}
          IFS='.' read -r -a V_PARTS <<< "$VERSION"

          # PRからsemverラベルを取得
          LABELS=$(gh pr view $PR_NUMBER --json labels -q '.labels.[].name')

          if echo "$LABELS" | grep -q "semver:major"; then
            echo "Bumping major version"
            V_PARTS[0]=$((V_PARTS[0] + 1))
            V_PARTS[1]=0
            V_PARTS[2]=0
          elif echo "$LABELS" | grep -q "semver:minor"; then
            echo "Bumping minor version"
            V_PARTS[1]=$((V_PARTS[1] + 1))
            V_PARTS[2]=0
          else
            echo "Bumping patch version (default)"
            V_PARTS[2]=$((V_PARTS[2] + 1))
          fi

          NEW_VERSION="${V_PARTS[0]}.${V_PARTS[1]}.${V_PARTS[2]}"
          NEW_TAG="v${NEW_VERSION}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "VERSION_NAME=$NEW_VERSION" >> $GITHUB_ENV

      # 6. pubspec.yamlのバージョンを更新
      - name: Update version in pubspec.yaml
        run: yq -i '.version = "${{ steps.versions.outputs.new_version }}+${{ github.run_number }}"' pubspec.yaml

      # 7. Flutter環境のセットアップとビルド
      - name: Set up Flutter
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          fvm install
      - name: Get Flutter packages
        run: fvm flutter pub get
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "STORE_FILE=upload-keystore.jks" >> $GITHUB_ENV
      - name: Build Android Release Files
        run: |
          fvm flutter build apk --release --split-per-abi \
            --build-name=${{ env.VERSION_NAME }} \
            --build-number=${{ github.run_number }} \
            --dart-define=NOVELTY_API_URL=${{ secrets.NOVELTY_API_URL }}
          fvm flutter build appbundle --release \
            --build-name=${{ env.VERSION_NAME }} \
            --build-number=${{ github.run_number }} \
            --dart-define=NOVELTY_API_URL=${{ secrets.NOVELTY_API_URL }}
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 8. リリース準備のコミットとタグ付け
      - name: Commit, Tag and Push
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          # mainブランチの最新状態に追従
          git fetch origin main
          git checkout -b release-prep ${{ github.sha }}
          git add pubspec.yaml
          git commit -m "chore(release): prepare for release ${{ steps.versions.outputs.new_tag }} [skip ci]"
          # 新しいコミットにタグを付ける
          git tag ${{ steps.versions.outputs.new_tag }}
          # タグをプッシュ
          git push origin ${{ steps.versions.outputs.new_tag }}

      # 9. GitHubリリースを作成
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.versions.outputs.new_tag }}" \
            --title "Release ${{ steps.versions.outputs.new_tag }}" \
            --notes-file RELEASE_NOTES.md \
            build/app/outputs/bundle/release/app-release.aab \
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk \
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
            build/app/outputs/flutter-apk/app-x86_64-release.apk